# UV docs for publishing
# https://docs.astral.sh/uv/guides/integration/github/#publishing-to-pypi

name: Publish package to PyPI
description: "Publish package to PyPI."
inputs:
  python-version:
    description: "Version of python"
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
    - name: Configure Git Credentials
      shell: bash
      # Set git user for commits
      # Email: ID+USERNAME@users.noreply.github.com
      # https://api.github.com/users/github-actions[bot]
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
    - name: Setup python
      uses: saritasa-nest/saritasa-python-open-source-boilerplate/.github/actions/setup_python@main
      with:
        version: ${{ inputs.python-version }}
    - name: Ensure tag matches pyproject version
      id: version-check
      shell: bash
      run: |
        TAG="${GITHUB_REF_NAME}"
        VERSION=$(uvx hatch version)
        echo "Tag: $TAG | pyproject: $VERSION"
        if [ "$TAG" != "$VERSION" ]; then
          echo "::error::Git tag ($TAG) does not match pyproject version ($VERSION)" >&2
          exit 1
        fi
        echo "package_version=$VERSION" >> "$GITHUB_OUTPUT"
    - name: Build
      shell: bash
      run: uv build
    - name: Publish new docs version
      shell: bash
      run: |
        uv run mike deploy --push --update-aliases ${{ steps.version-check.outputs.package-version }} latest
    - name: Publish
      shell: bash
      run: uv publish
