name: Setup python
description: "Setup python."
inputs:
  version:
    description: "Version of python"
    required: false
    default: ""
outputs:
  cache-prefix:
    description: "Prefix for cache"
    value: ${{ steps.set-cache-prefix.outputs.cache-prefix }}
runs:
  using: "composite"
  steps:
    - name: Install uv
      id: setup-uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
        activate-environment: "true"
        cache-python: "true"
    - name: Set cache prefix in env
      id: set-cache-prefix
      shell: bash
      run: echo "cache-prefix=${{ runner.os }}-${{ github.job }}-${{ steps.setup-uv.outputs.python-version }}" >> $GITHUB_OUTPUT
    - name: Cache pre-commit
      uses: actions/cache@v5
      with:
        path: ~/.cache/pre-commit
        key: ${{ steps.set-cache-prefix.outputs.cache-prefix }}-pre-commit-${{ hashFiles('**/.pre-commit-config.yaml') }}
    - name: Cache mypy
      uses: actions/cache@v5
      with:
        path: "**/.mypy_cache"
        key: ${{ steps.set-cache-prefix.outputs.cache-prefix }}-mypy-${{ hashFiles('**/uv.lock') }}
    - name: Sync dependencies
      shell: bash
      if: steps.setup-uv.cache-hit != 'true'
      run: uv sync --locked --all-groups
