name: Run pre-commit hooks

on:
  pull_request:
  push:
    branches: [
      main,
      staging,
      develop
    ]

concurrency:
  group: ${{ '{{' }} github.workflow }}-${{ '{{' }} github.ref }}
  cancel-in-progress: true

env:
  # Fallback to plain text output for reducing docker output
  # https://github.com/docker/compose/issues/8753#issuecomment-934473781
  BUILDKIT_PROGRESS: plain

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: [
          "{{ min_python_version | round(2) }}",
          "{{ min_python_version + 0.01 | round(2) }}",
          "{{ min_python_version + 0.02 | round(2) }}",
        ]
    steps:
      - name: Run
        uses: saritasa-nest/saritasa-python-open-source-boilerplate/.github/actions/run_pre_commit@main
        with:
          python-version: ${{ '{{' }} matrix.python-version }}
